In [ ]:
import numpy as np 
a = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        ])      
# printing the array
# b = np.arange(4)
# print(b)
#       rows columns
print(a[[1,2],[1,0]]) # 5 7
print(a[[0,2]])
print(b[[0,2]])
print("#####")
print(a[ : ,:1])
a[2,0]=22
print(a)
print("Sum: ",a.sum())
print("Mean: ",a.mean())
print("Std: ",a.std())
print("Var: ",a.var())
a+=20
print(a)




[5 7]
[[1 2 3]
 [7 8 9]]


In [86]:
import numpy as np 
import random
a = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        ]) 
a = a[(a>=5) | (a==1) ]
print(a,"1")
b = np.arange(5)
print(b,"2")
b<=3
print(b<=3,"3")

c = np.random.randint(100,size=(3,3))
print(c,"5")
print(a[(a > 50) & (a%2==0)],"4")
# for i in a :
#     print(a,end=" ")


[1 5 6 7 8 9] 1
[0 1 2 3 4] 2
[ True  True  True  True False] 3
[[30 54 90]
 [36 57  3]
 [63 40 39]] 5
[] 4


In [ ]:
import numpy as np
import random

print(np.random.random(size=4))
print(np.random.normal(size=2))
print(np.random.rand(3,2))
np.arange(4).reshape(2,2)
np.linspace(0,5,4)
np.zeros(4).reshape(2,2)
np.zeros((3,3))
np.empty((3,2))


array([[0.6010217 , 0.68704081],
       [0.24351604, 0.20278901],
       [0.53307559, 0.20178837]])